import Header from "./header";
import NavBar from "./navbar";
import Head from "next/head";

export default function Layout(props) {
  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>psy-test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className="sticky top-0" />
      <NavBar className="sticky top-0" />
      <div className="flex-1 overflow-auto">{props.children}</div>
    </div>
  );
}
